### ISSUE TITLE
Wishlist won't open

### ISSUE THREAD

**Issue by Shhizuha** [Lexiebean/AtlasLoot#107]
Seemingly out of the blue the wishlist stopped working on one of my characters with the error code of "ERROR: Interface\AddOns\AtlasLoot\Core\WishList.lua:266: attempt to concatenate a nil value"

Wishlist won't open at all, same message appears when trying to add items to it on said character.

**Comment by Lexiebean** [comment]
Can you please upload your AtlasLoot.lua file, found in `/TurtleWoW/WTF/Account/ACCOUNT/Nordanaar/CharacterName/SavedVariables/` or send it to me via discord?

**Comment by Shhizuha** [comment]
Sent via discord (Saber)

**Comment by Shhizuha** [comment]
Ended up moving the file out to another folder so the game could gen a fresh one(which worked), then remade list via reading what I still needed off the og. So it's def something in that file, what exactly tho idk.

**Comment by Lexiebean** [comment]
Ahh sorry! I'd forgotten about this. 

I've been travelling around the world. Literally just got home a few hours ago

**Comment by Shhizuha** [comment]
All good friend

**Comment by Lexiebean** [comment]
Sorry for taking so long!

If you're still having this issue, you'll need to edit the `AtlasLoot.lua` you sent me.

You'll need to change `KCCommanderAnderson` to `KCCommanderAndreon`
