### ISSUE TITLE
Missing LW Grifter's Set

### ISSUE THREAD

**Issue by Lexiebean** [Lexiebean/AtlasLoot#2]
What level does each unlock at?

**Comment by Platinumcoated** [comment]
Grifter's Armor

Grifter's Belt - 200 https://database.turtle-wow.org/?item=83403
Grifter's Boots - 200 https://database.turtle-wow.org/?item=83405
Grifter's Gauntlets - 200 https://database.turtle-wow.org/?item=83404
Grifter's Leggings - 205 https://database.turtle-wow.org/?item=83402
Grifter's Cover - 210 https://database.turtle-wow.org/?item=83400
Grifter's Tunic - 210 https://database.turtle-wow.org/?item=83401

Primalist's Trappings

Primalist's Boots - 275 https://database.turtle-wow.org/?item=81065
Primalist's Gloves - 275 https://database.turtle-wow.org/?item=81061
Primalist's Headdress - 275 https://database.turtle-wow.org/?item=81063
Primalist's Pants - 280 https://database.turtle-wow.org/?item=81064
Primalist's Shoulders - 280 https://database.turtle-wow.org/?item=81062
Primalist's Vest - 285 https://database.turtle-wow.org/?item=81066

while I can't say for sure, I remember the Grifter set being bad for skilling up, I think it was gray from the moment you can learn it. I can however confirm that the entire Primalist set is gray at skill lvl 300

**Comment by Lexiebean** [comment]
Belt, Boot, Gauntlets: Yellow @ 215, green @ 220, grey @ 225

Cover & Leggings: Yellow @ 225, green @ 230, grey @ 235

Tunic: Yellow @ 235, green @ 240, grey @ 245

**Comment by Lexiebean** [comment]
Feathered Breastplate is no longer tribal LW, and open to everyone

**Comment by Lexiebean** [comment]
Primalist's Boots - 290 yellow - 291 green - 295 grey
Primalist's Gloves - 285 yellow - 290 green - 295 grey
Primalist's Headdress - 290 yellow - 291 green - 295 grey
Primalist's Pants - 290 yellow - 291 green - 295 grey
Primalist's Shoulders - 285 yellow - 290 green - 295 grey
Primalist's Vest - 285 yellow - 290 green - 291 green - 295 grey

**Comment by Lexiebean** [comment]
Done! Added to the next release!
(This took me about 2hrs to complete)
