### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by burner1024** [Lexiebean/AtlasLoot#45]
Or am I doing something wrong?

![Captura desde 2023-07-05 21-35-22](https://github.com/Lexiebean/AtlasLoot/assets/1279852/dde77cd9-c9ca-450c-b1c3-4f4eb587832e)
![Captura desde 2023-07-05 21-35-27](https://github.com/Lexiebean/AtlasLoot/assets/1279852/c1a65254-3a95-4d50-8f3a-7cdd163b8d56)

**Comment by Lexiebean** [comment]
This happens after you've cleared your WDB or if you have never seen those items before.

If you press the Query Server button at the bottom, the after a second or 2 right click on any item, it should load them all.

(Also whoever originally added Nerubian Overseer did a terrible job)

**Comment by burner1024** [comment]
Of course, I did that.
![Captura desde 2023-07-11 04-49-17](https://github.com/Lexiebean/AtlasLoot/assets/1279852/d66e91b3-aff5-4143-96e1-0a016d149aaf)
