### ISSUE TITLE
Sets/Collection errors for tier sets

### ISSUE THREAD

**Issue by EyeOfTheBeast** [Lexiebean/AtlasLoot#57]
Wrong icons for the boots:
![image](https://github.com/Lexiebean/AtlasLoot/assets/142637959/ca398e3b-1b96-46b1-ad49-ce53c69f7c52)
![image](https://github.com/Lexiebean/AtlasLoot/assets/142637959/ab1bdc91-56df-4fb9-af16-8834b2b135a8)
'Waist' should be 'Hands':
![image](https://github.com/Lexiebean/AtlasLoot/assets/142637959/114354f1-33ff-49ba-b768-ad1cf36e4d2a)

**Comment by Lexiebean** [comment]
Thanks! I bet that bug has been in since the vanilla version.

@cyaohiri sorry I missed your PR when I was messing with the 1.1.0 branch

**Comment by cyaohiri** [comment]
> @cyaohiri sorry I missed your PR when I was messing with the 1.1.0 branch

No worries, but seems like you forgot to apply the changes for #58.
