### ISSUE TITLE
Caverns of Time: Black Morass issues

### ISSUE THREAD

**Issue by EyeOfTheBeast** [Lexiebean/AtlasLoot#64]
- The Shard of Eternity trinket that drops off Antnormi has the wrong icon (it should have the same icon as a Large Brilliant Shard): 

https://database.turtle-wow.org/?item=61014

![image](https://github.com/Lexiebean/AtlasLoot/assets/142637959/a7056a52-d3cb-4487-b12a-b1f8b0f7f913)

- Trash drops from the Caverns of Time: Black Morass are missing completely. See here for a list of the BoE unique blue drops in this dungeon: https://database.turtle-wow.org/?npc=61318#drop:0+1-12

**Comment by Lexiebean** [comment]
Thanks! Fixed in 1e00103a6513464787c36810e2fc5edd5efcf39f
