### ISSUE TITLE
AtlasLoot.lua problem with Atlas

### ISSUE THREAD

**Issue by Nonameby** [Lexiebean/AtlasLoot#74]
version 1.1.0; line 1829 it wasnt there on version 1.0.9
this part blocks Atlas from access to some loot table. pvp, world events, crafting, etc. 
local pagename = getglobal(this:GetName().."_Name"):GetText()
		for k,v in ipairs(AtlasLoot_HewdropDown) do
			if not (type(v[1]) == "table") then
				for k2, v2 in pairs(v) do
					for k3, v3 in pairs(v2) do
						for k4, v4 in pairs(v3) do
							if not (type(v4[1]) == "table") then
								if v4[1] == pagename then
									AtlasLoot_HewdropClick(v4[2],v4[1],v4[3])
								end
							end
						end
					end
				end
			end
		end

**Comment by cyaohiri** [comment]
Are you using Atlas for Turtle WoW? You can get it here: https://github.com/Nonameby/Atlas

**Comment by Lexiebean** [comment]
Atlas will need to update.

I made some changes to the Dewdrop library and renamed it to Hewdrop. Maybe that's the conflict.

Either way, I don't work on Atlas, just AtlasLoot.

**Comment by Nonameby** [comment]
I am working on Atlas.
https://github.com/Nonameby/Atlas
Your change makes it impossible to use any version of Atlas Addon (new or old before my changes) . 
Atlas worked just fine with AtlasLoot until you added this part few days ago.
Even if I can manage to fix it on Atlas in the future (which i'm not sure of :)) I can't make changes on old versions that people use. If this Code is crucial and you can't delete maybe you can rework that part so it won't have conflict with Atlas addon.
