### ISSUE TITLE
wishlist error

### ISSUE THREAD

**Issue by pmaccamp** [Lexiebean/AtlasLoot#77]
Get this when I try to search for "broken".  Saw your debug code and turned it on before checking for nil in my local version :)

![image](https://github.com/Lexiebean/AtlasLoot/assets/1526649/bfdae546-dcb0-40ee-b5f3-84f1483efe7d)

**Comment by Lexiebean** [comment]
That debug if huge! You're amazing! Thank you!

I can't actually reproduce this. But maybe it was already fixed in aa9d3ef?
