### ISSUE TITLE
Discord issue

### ISSUE THREAD

**Issue by Lexiebean** [Lexiebean/AtlasLoot#81]
![image](https://github.com/Lexiebean/AtlasLoot/assets/6937574/e27fbf07-8039-4f28-91a5-669c4614f8f8)

**Comment by Lexiebean** [comment]
Check https://discord.com/channels/466622455805378571/466627627554439178/1177369139904532601

**Comment by EyeOfTheBeast** [comment]
I think AtlasLoot is correct here and this bug report is a false alarm. Wowhead Classic shows that the Gemstone of Bloodaxe has a 40% drop chance and the Mark of the Dragon Lord is at a 1.4% drop chance.

This person's proposed actual drop rates would be too low to account for this data on Wowhead Classic. They may be misunderstanding how loot groups work.
