### ISSUE TITLE
Missing LW Red Dragonscale Set

### ISSUE THREAD

**Issue by Platinumcoated** [Lexiebean/AtlasLoot#9]
crafted by Dragonscale Leatherworking

**Red Dragon Mail (0/4)**

**Red Dragonscale Breastplate** - skill 300 https://database.turtle-wow.org/?item=15047
originally from Vanilla, modified by Turtle

taught by - https://database.turtle-wow.org/?item=15730 - dropped by General Drakkisath
**^^these are already in**

**Red Dragonscale Boots** - skill 295 https://database.turtle-wow.org/?item=65002
-added by Turtle
taught by:   
- https://database.turtle-wow.org/?npc=7866 Peter Galen \<Master Dragonscale Leatherworker\>
- https://database.turtle-wow.org/?npc=7867 Thorkaf Dragoneye \<Master Dragonscale Leatherworker\>
- https://database.turtle-wow.org/?item=83533 - this pattern has no source (unobtainable)

**Red Dragonscale Shoulders** - skill 300 https://database.turtle-wow.org/?item=65001
-added by Turtle
taught by:
 - https://database.turtle-wow.org/?item=83537 - dropped by elite lvl58 Red Dragonkins in Wetlands

**Red Dragonscale Leggings** - skill 295 https://database.turtle-wow.org/?item=65000
-added by Turtle
taught by pattern:  -  https://database.turtle-wow.org/?item=83538
pattern sold by:
- https://database.turtle-wow.org/?npc=4883 Krak \<Armorer\>
- https://database.turtle-wow.org/?npc=2679 Wenna Silkbeard \<Special Goods Dealer\>

**Comment by Lexiebean** [comment]
Missing Stormscale Leggings
Missing Dragonscale Leggings
