### ISSUE TITLE
Intact Pounder Mainframe (Crowd Pummeler 9-60)

### ISSUE THREAD

**Issue by GoldenSpatula69** [Lexiebean/AtlasLoot#92]
The following item is missing from a boss in Gnomeregan. It has a low drop rate (0.8%) and it begins a quest to obtain a mount.

TurtleWoW Database: [https://database.turtle-wow.org/?item=81275#dropped-by]

**Comment by EyeOfTheBeast** [comment]
It already is in there:
![image](https://github.com/Lexiebean/AtlasLoot/assets/142637959/9f7fb892-38c6-4326-b85a-e11c8befcb18)

**Comment by GoldenSpatula69** [comment]
> It already is in there: ![image](https://private-user-images.githubusercontent.com/142637959/299813656-9f7fb892-38c6-4326-b85a-e11c8befcb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODkxNDUsIm5iZiI6MTcwNjc4ODg0NSwicGF0aCI6Ii8xNDI2Mzc5NTkvMjk5ODEzNjU2LTlmN2ZiODkyLTM4YzYtNDMyNi1iODVhLWUxMWM4YmVmY2IxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMjAwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTZmZTkyNTFmZDkyOWIxZjNkNDA1MWUyNjE2MGUzNjE5ZmY1MzRmYjc4MzhmM2M2OWU1Mzc2OWI1ZDJiMWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OijyJgl5MlCPXsCOsAp7a4WiWnqZezrGY0eaEw7dWak)

Must have been added recently then :D
