### ISSUE TITLE
Pattern not showing correctly when mouse over 

### ISSUE THREAD

**Issue by Darthblaider** [Lexiebean/AtlasLoot#99]
![image](https://github.com/Lexiebean/AtlasLoot/assets/11171480/676a2535-af4b-4704-ac69-b08e4fe13d04)
Was browsing for Dawnstone Hammer in atlas and it showed recipe for sulfuron hammer but the tooltip for dawnstone when moused over

**Comment by Lexiebean** [comment]
Fixed in c52267c
